version: "3.9"
services:
    gateway:
        build:
            context: gateway/docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "8080:8080"
            - "8081:8081"
            - "8082:8082"
            - "8083:8083"
        depends_on:
            - frontend
            - api
            - mailer
            - rabbitmq

    frontend:
        build:
            context: frontend/docker/development/nginx
        depends_on:
            - frontend-node

    frontend-node:
        build:
            context: frontend/docker/development/node
        environment:
            WDS_SOCKET_PORT: 0
            REACT_APP_AUTH_URL: http://localhost:8081
            REACT_APP_BACKEND_API_URL: http://localhost:8081/api
        volumes:
            - ./frontend:/app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
        tty: true

    frontend-node-cli:
        build:
            context: frontend/docker/development/node
        volumes:
            - ./frontend:/app

    api:
        build:
            context: api/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./api:/app
        depends_on:
            - api-php-fpm

    api-php-fpm:
        build:
            context: api/docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            PHP_IDE_CONFIG: serverName=API
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: domains-manager
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USER: app
            MAILER_PASSWORD: secret
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://localhost:8080
            JWT_ENCRYPTION_KEY: secret
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        volumes:
            - ./api:/app
        secrets:
            - jwt_public_key
            - jwt_private_key
        depends_on:
            - mailer
            - rabbitmq
            - api-postgres

    api-php-cli:
        build:
            context: api/docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: domains-manager
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USER: app
            MAILER_PASSWORD: secret
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://localhost:8080
            JWT_ENCRYPTION_KEY: secret
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        volumes:
            - ./api:/app
        secrets:
            - jwt_public_key
            - jwt_private_key
        depends_on:
            - mailer
            - rabbitmq
            - api-postgres

    api-php-worker:
        build:
            context: api/docker
            dockerfile: development/php-worker/Dockerfile
        environment:
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: domains-manager
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USER: app
            MAILER_PASSWORD: secret
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://localhost:8080
            JWT_ENCRYPTION_KEY: secret
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        volumes:
            - ./api:/app
        secrets:
            - jwt_public_key
            - jwt_private_key
        ports:
            - "8084:9001" # Access to supervisor GUI. username/password - root/root
        depends_on:
            - mailer
            - rabbitmq
            - api-postgres

    api-postgres:
        image: postgres:13.4-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: domains-manager
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

    mailer:
        image: mailhog/mailhog

    mailer-secondary:
        image: schickling/mailcatcher
        ports:
            - "8085:1080"

    rabbitmq:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: rabbit
        volumes:
            - ./rabbitmq/docker/enabled_plugins:/etc/rabbitmq/enabled_plugins

secrets:
    jwt_public_key:
        file: ./docker/development/secrets/jwt_public.key
    jwt_private_key:
        file: ./docker/development/secrets/jwt_private.key

volumes:
    api-postgres:
